In [11]:
import numpy as np
import adaboost

In [12]:
data_mat,class_labels = adaboost.load_simple_data()
classifier_array = adaboost.adaboost_train_ds(data_mat,class_labels,9)

D: [[ 0.2  0.2  0.2  0.2  0.2]]
class_est: [[-1.  1. -1. -1.  1.]]
agg_class_est: [[-0.69314718  0.69314718 -0.69314718 -0.69314718  0.69314718]]
total error:  0.2
D: [[ 0.5    0.125  0.125  0.125  0.125]]
class_est: [[ 1.  1. -1. -1. -1.]]
agg_class_est: [[ 0.27980789  1.66610226 -1.66610226 -1.66610226 -0.27980789]]
total error:  0.2
D: [[ 0.28571429  0.07142857  0.07142857  0.07142857  0.5       ]]
class_est: [[ 1.  1.  1.  1.  1.]]
agg_class_est: [[ 1.17568763  2.56198199 -0.77022252 -0.77022252  0.61607184]]
total error:  0.0


D:\ProgramData\Anaconda3\lib\site-packages\numpy\core\_methods.py:26: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return umr_maximum(a, axis, None, out, keepdims)


In [13]:
classifier_array

[{'alpha': 0.6931471805599453, 'dim': 0, 'ineq': 'lt', 'thresh': 1.3},
 {'alpha': 0.9729550745276565, 'dim': 1, 'ineq': 'lt', 'thresh': 1.0},
 {'alpha': 0.8958797346140273,
  'dim': 0,
  'ineq': 'lt',
  'thresh': 0.90000000000000002}]

In [14]:
adaboost.adaboost_classify([0,0],classifier_array)

[[-0.69314718]]
[[-1.66610226]]
[[-2.56198199]]


matrix([[-1.]])

In [15]:
adaboost.adaboost_classify([[5,5],[0,0]],classifier_array)

[[ 0.69314718]
 [-0.69314718]]
[[ 1.66610226]
 [-1.66610226]]
[[ 2.56198199]
 [-2.56198199]]


matrix([[ 1.],
        [-1.]])

In [16]:
dat_arr,label_arr = adaboost.load_data_set('horseColicTest.txt')

In [17]:
classifier_array = adaboost.adaboost_train_ds(dat_arr,label_arr,10)

D: [[ 0.01492537  0.01492537  0.01492537  0.01492537  0.01492537  0.01492537
   0.01492537  0.01492537  0.01492537  0.01492537  0.01492537  0.01492537
   0.01492537  0.01492537  0.01492537  0.01492537  0.01492537  0.01492537
   0.01492537  0.01492537  0.01492537  0.01492537  0.01492537  0.01492537
   0.01492537  0.01492537  0.01492537  0.01492537  0.01492537  0.01492537
   0.01492537  0.01492537  0.01492537  0.01492537  0.01492537  0.01492537
   0.01492537  0.01492537  0.01492537  0.01492537  0.01492537  0.01492537
   0.01492537  0.01492537  0.01492537  0.01492537  0.01492537  0.01492537
   0.01492537  0.01492537  0.01492537  0.01492537  0.01492537  0.01492537
   0.01492537  0.01492537  0.01492537  0.01492537  0.01492537  0.01492537
   0.01492537  0.01492537  0.01492537  0.01492537  0.01492537  0.01492537
   0.01492537]]
class_est: [[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1

D:\ProgramData\Anaconda3\lib\site-packages\numpy\core\_methods.py:26: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return umr_maximum(a, axis, None, out, keepdims)


In [18]:
test_arr,test_label_arr = adaboost.load_data_set('horseColicTest.txt')

In [19]:
prediction10 = adaboost.adaboost_classify(test_arr,classifier_array)

[[ 0.42720766]
 [ 0.42720766]
 [ 0.42720766]
 [ 0.42720766]
 [ 0.42720766]
 [ 0.42720766]
 [ 0.42720766]
 [ 0.42720766]
 [ 0.42720766]
 [ 0.42720766]
 [ 0.42720766]
 [ 0.42720766]
 [ 0.42720766]
 [ 0.42720766]
 [ 0.42720766]
 [ 0.42720766]
 [ 0.42720766]
 [ 0.42720766]
 [ 0.42720766]
 [ 0.42720766]
 [ 0.42720766]
 [ 0.42720766]
 [ 0.42720766]
 [ 0.42720766]
 [ 0.42720766]
 [ 0.42720766]
 [ 0.42720766]
 [ 0.42720766]
 [ 0.42720766]
 [ 0.42720766]
 [ 0.42720766]
 [ 0.42720766]
 [ 0.42720766]
 [ 0.42720766]
 [ 0.42720766]
 [ 0.42720766]
 [ 0.42720766]
 [ 0.42720766]
 [ 0.42720766]
 [ 0.42720766]
 [ 0.42720766]
 [ 0.42720766]
 [ 0.42720766]
 [ 0.42720766]
 [ 0.42720766]
 [ 0.42720766]
 [ 0.42720766]
 [ 0.42720766]
 [ 0.42720766]
 [ 0.42720766]
 [ 0.42720766]
 [ 0.42720766]
 [ 0.42720766]
 [ 0.42720766]
 [ 0.42720766]
 [ 0.42720766]
 [ 0.42720766]
 [ 0.42720766]
 [ 0.42720766]
 [ 0.42720766]
 [ 0.42720766]
 [ 0.42720766]
 [ 0.42720766]
 [ 0.42720766]
 [ 0.42720766]
 [ 0.42720766]
 [ 0.42720

In [20]:
err_arr = np.mat(np.ones((67,1)))

In [21]:
err_arr[prediction10!=np.mat(test_label_arr).T].sum()

20.0