In [1]:
import numpy as np

In [4]:
a = [[1,2],[3,4]]
b = [[5,6],[7,8]]
c = [1,2,3,4]
d = [5,6,7,8]

In [5]:
m1 = np.mat(a)
m2 = np.mat(b)
m3 = np.mat(c)
m4 = np.mat(d)

In [7]:
print(m3)
print(m4)
print(np.multiply(m3,m4))

[[1 2 3 4]]
[[5 6 7 8]]
[[ 5 12 21 32]]


In [8]:
np.multiply(m3,m4.transpose())

matrix([[ 5, 10, 15, 20],
        [ 6, 12, 18, 24],
        [ 7, 14, 21, 28],
        [ 8, 16, 24, 32]])

In [10]:
m5 = np.mat([1,2])

In [12]:
m1 * m5.T

matrix([[ 5],
        [11]])